#!/bin/bash
#
# vm-makeover <uservm> <vm-image-full-path> <vm-hostname> <vm-ip> <netmask> <gateway> <scriptdir>
#
# Modify VM image file.
#
# Should only be sudo run by vm-makedisk
#
# V2.0 - 10/4/11, Cindy Zheng, zhengc@sdsc.edu
# 

if [ $# -ne 7 ];
then
  /bin/rm -f $1;
  exit 1
fi

#
# Check VM mount point
#
if [ -d /tmp/$1 ];
then
  /bin/mountpoint -q /tmp/$1;
  if [ $? -eq 0 ];
  then
    /bin/umount /tmp/$1;
    if [ $? -ne 0 ];
    then
      /bin/rm -f $2;
      exit 2
    fi
  fi
else
  /bin/mkdir /tmp/$1
fi

#
# Mount the disk image in user's home directory
#
/usr/bin/lomount -diskimage $2 -partition 1 /tmp/$1
if [ $? -ne 0 ];
then
  /bin/rm -f $2;
  exit 3
fi

#
# Modify VM disk image
#
# Modify grub file
#
line=$(/bin/grep "default=0" /tmp/$1/boot/grub/grub.conf)
if [ -n "$line" ];
then
  /bin/sed -i 's/default=0/default=1/' /tmp/$1/boot/grub/grub.conf
fi

#
# Save then replace ifcfg-eth0
#
/bin/cp /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0 /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0.old
/opt/rocks/bin/rocks report host interface $1 | /bin/grep DEVICE | /bin/cat > /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0
/opt/rocks/bin/rocks report host interface $1 | /bin/grep HWADDR | /bin/cat >> /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0
/opt/rocks/bin/rocks report host interface $1 | /bin/grep IPADDR | /bin/cat >> /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0
/opt/rocks/bin/rocks report host interface $1 | /bin/grep NETMASK | /bin/cat >> /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0
/opt/rocks/bin/rocks report host interface $1 | /bin/grep BOOTPROTO | /bin/cat >> /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0
/opt/rocks/bin/rocks report host interface $1 | /bin/grep ONBOOT | /bin/cat >> /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0
/opt/rocks/bin/rocks report host interface $1 | /bin/grep MTU | /bin/cat >> /tmp/$1/etc/sysconfig/network-scripts/ifcfg-eth0

#
# Get old hostname
#
vminfo=$(/bin/grep "^HOSTNAME" /tmp/$1/etc/sysconfig/network)
if [ -z "$vminfo" ];
then
  echo "Warning: can't find the original hostname in /etc/sysconfig/network"
else
  oldhostfull=$(/bin/echo $vminfo | /bin/cut -d'=' -f2);
  oldhostshort=$(/bin/echo $oldhostfull | /bin/cut -d'.' -f1)
fi

#
# Get short new hostname
#
newhostshort=$(/bin/echo $3 | /bin/cut -d'.' -f1)

#
# Modify network file
#
/bin/sed -i 's/HOSTNAME/#HOSTNAME/' /tmp/$1/etc/sysconfig/network
/bin/echo "HOSTNAME=$3" >> /tmp/$1/etc/sysconfig/network
/bin/sed -i 's/GATEWAY/#GATEWAY/' /tmp/$1/etc/sysconfig/network
/bin/echo "GATEWAY=$6" >> /tmp/$1/etc/sysconfig/network

#
# Modify resolv.conf
#
/bin/cp $7/resolv.conf /tmp/$1/etc/resolv.conf
/bin/chmod 644 /tmp/$1/etc/resolv.conf

#
# Add root and user ssh public keys
#
/bin/cat /tmp/$1.tmp >> /tmp/$1/root/.ssh/authorized_keys

#
# Modify hosts file
#
/bin/sed -i "s/$oldhostfull/$3/g" /tmp/$1/etc/hosts
/bin/sed -i "s/$oldhostshort/$newhostshort/g" /tmp/$1/etc/hosts

#
# Modify auto.home
#
/bin/sed -i "s/$oldhostshort/$newhostshort/g" /tmp/$1/etc/auto.home

#
# Modify httpd.conf
#
/bin/sed -i "s/$oldhostfull/$3/g" /tmp/$1/etc/httpd/conf/httpd.conf

/bin/umount /tmp/$1

exit 0
