#!/bin/bash
#
# vm-makedisk <vm-name> <vm-image-full-path> <vm-hostname> <vm-ip> <netmask> <gateway> <vmsize> <vm-home-path> <scriptdir> <bootorder> <userkeyfile>
#
# Place then modify VM image file.
#
# Only should be run by vm-deploy
#
# V2.0 - 10/4/11, Cindy Zheng, zhengc@sdsc.edu
# 

if [ $# != 11 ];
then
  exit 1
fi

#
# Quit if the vm image file already exist
#
if [ -e $2 ];
then
  exit 2
fi

#
# How much disk space is available
#
/bin/touch $2
diskinfo=$(df $2 | tail -1)
if [ -z "$diskinfo" ];
then
  exit 3
fi
space=$(echo $diskinfo | cut -d' ' -f4)
# debugging echo
echo "Available disk space = $space"

#
# Enough disk space?
#
if [ $7 -gt $space ];
then
# debugging echo
  echo "Need $7 KB and only $space KB available";
  exit 4
fi

#
# Copy VM image from user home directory
#
echo "Copying VM image $8... May take a few minutes"
cp $8 $2

# debugging echo
echo "sudo $9/vm-makeover $1 $2 $3 $4 $5 $6 $9 ${10} ${11}"
sudo $9/vm-makeover $1 $2 $3 $4 $5 $6 $9 ${10} ${11}
if [ $? -eq 0 ];
then
  exit 0
fi
let "result=$?+4"
# debugging echo
echo "vm-makeover returned $result"
exit $result
