#!/bin/bash
#
# vm-new creates a new vm and give user access to the disk image file
# It should be only sudo-run by vm-deploy
#
# V2.0 - 10/4/11, Cindy Zheng, zhengc@sdsc.edu
#

#
# vm-new $vmcontainer $uservm $vmip $availableip $nettype $userhomedir
#

if [ $# != 6 ];
then
  exit 5
fi

#
# Create a new VM
#
/opt/rocks/bin/rocks add host vm $1 membership="hosted vm" name=$2
if [ $? -ne 0 ];
then
  exit 1
fi

/opt/rocks/bin/rocks set host interface subnet $2 eth0 $5
if [ $? -ne 0 ];
then
  /opt/rocks/bin/rocks remove host $2;
  exit 2
fi
/opt/rocks/bin/rocks set host interface ip $2 eth0 $3 
if [ $? -ne 0 ];
then
  /opt/rocks/bin/rocks remove host $2;
  exit 3
fi
/opt/rocks/bin/rocks set host attr $2 os linux

info=$(/opt/rocks/bin/rocks report host interface $2 | grep MTU)
if [ -z "$info" ];
then
  exit 4
fi

#
# New VM is created successfully
# Mark the ip# used in Availableip
#
sed -i "s/$3/#$3/" $4

exit 0
