#!/bin/bash
#
# vm-remove <uservm>
#
# Remove a VM which was created with vm-deploy script
# It should be only run under normal user account
# Although it does permit root to remove any VM
#
# V2.0 - 10/4/11, Cindy Zheng, zhengc@sdsc.edu
#

scriptdir=/opt/vm-scripts

if [ $# != 1 ];
then
  echo "Please specify the name of VM to be removed";
  echo "To remove multiple VMs with the same base name, specify the base name";
  echo "Usage: vm-remove vm-name";
  exit 1
fi

#
# Is the VM exist
#
/opt/rocks/bin/rocks list host | grep $1 > /tmp/remove-$1.txt
if [ ! -s /tmp/remove-$1.txt ];
then
  echo "VM $1 does not exist";
  exit 2
fi

#
# If the user own the VM, remove VM and free the resources
#
username=$(whoami)
if [ "$username" != "root" ];
then
  vmuser=$(echo "$1" | cut -d'-' -f2);
  if [ "$vmuser" != "$username" ];
  then
    echo "Permission denied: Only root or user $vmuser can remove $1";
    exit 3
  fi
fi

#
# Get VM names in an array
declare -a vmname
declare -i i=0
while read;
do
  vmname[ $i ]=$(echo "$REPLY" | cut -d':' -f1);
  ((i = i + 1));
done < /tmp/remove-$1.txt
vmcount=$i

#
# allow user to confirm
#
echo "Ready to remove the following VMs:"
/bin/cat /tmp/remove-$1.txt
echo "Confirm (y) or Quit (n)?"
read answer
if [ $answer != "y" ];
then
  echo "Terminate per user request - no VM is removed";
  exit
fi

#
# Start loop thru the VMs
#
let i=0
while [ $i -lt $vmcount ]
do
  echo "sudo $scriptdir/vm-free ${vmname[$i]} $scriptdir/AvailableIP";
  sudo $scriptdir/vm-free ${vmname[$i]} $scriptdir/AvailableIP
  if [ $? -eq 0 ];
  then
    echo "${vmname[$i]} has been successfully removed and resources freed";
  elif [ $? -eq 1 ];
  then
    echo "Internal error: number of arguments mismatch when vm-remove ran vm-free"
    exit 4
  elif [ $? -eq 2 ];
  then
    echo "vm-free: Failed to stop ${vmname[$i]}"
    echo "Please report to the system administrators"
    exit 5
  elif [ $? -eq 3 ];
  then
    echo "vm-free: Failed to remove ${vmname[$i]}"
    echo "Please report to the system administrators"
    exit 5
  else
    echo "vm-free: Failed to remove ${vmname[$i]} disk image file"
    echo "Please manually remove the disk image file or report to your system administrator"
    exit 6
  fi
  (( i = i + 1 ))
done
/bin/rm /tmp/remove-$1.txt
exit 0
